// app/layout.jsx
import { Analytics } from "@vercel/analytics/next"
import {
  Geist,
  Geist_Mono,
  Inter,
  Noto_Serif,
  Public_Sans,
} from "next/font/google";
import "./globals.css";
import { ReactLenis } from "lenis/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Project fonts
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
  display: "swap",
});

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${notoSerif.variable} ${publicSans.variable} antialiased`}
      >
        <ReactLenis root>
          {children}
        </ReactLenis>
        <Analytics />
      </body>
    </html>
  );
}
